config/routes.rb
Rails.application.routes.draw do

 root "artiszoo#index"

  get "artiszoos" => "artiszoo#index"

  get "artiszoos/:id" => "artiszoo#show", as: :artiszoo
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # temporaryly quoted out: root "animals#index"

  resources :animals
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :artiszoo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artiszoo.rb
class Artiszoo < ApplicationRecord
  has_many :animals
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
  end
  def show
    @animal = Animal.find(params[:id])
  end
  def new
    @animal = Animal.new
  end
  def create
    animal_params = params.require(:animal).permit(:name, :food, :image_url, :artiszoo_id)

    @animal = Animal.new(animal_params)

    if @animal.save
       redirect_to @animal
    else
       render 'new'
    end
  end

  def edit
    @animal = Animal.find(params[:id])
  end
  def update
    @animal = Animal.find(params[:id])

    animal_params = params.require(:animal).permit(:name, :food, :image_url, :artiszoo_id)

    if @animal.update_attributes(animal_params)
      redirect_to @animal
    else
      render 'edit'
    end
  end
  def destroy
    @animal = Animal.find(params[:id])

    @animal.destroy

    redirect_to animals_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artiszoo_controller.rb
class ArtiszooController < ApplicationController

  def index
   @artiszoos = Artiszoo.all
  end

  def show
     @artiszoo = Artiszoo.find(params[:id])
     @animals =@artiszoo.animals
  end

 end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artiszoo_helper.rb
module ArtiszooHelper
end

app/views/animals/_form.html.erb
<%= form_for @animal do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :food %>
  <%= f.text_field :food %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.label :artiszoo_id %>
  <%= f.text_field :artiszoo_id %>

  <%= f.submit (@animal.new_record? ? "Create" : "Update") %>
<% end %>

app/views/animals/edit.html.erb
<h1>Edit Animal</h1>

<%=render "form"%>

app/views/animals/index.html.erb
<h1>Animals</h1>

<% @animals.each do |animal| %>
<ul><li>
<p><%= link_to animal.name, animal_path(animal.id) %></p>
</li></ul>

<%end%>

<br></br>

<hr>
<%= link_to "[New Animal]" , new_animal_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%=render "form"%>

app/views/animals/show.html.erb
<h1><%= @animal.name %></h1>

<h2><p>Food: <%= @animal.food %></p></h2>
<%= image_tag @animal.image_url %>
<hr>
<%= link_to "[Edit]", edit_animal_path(@animal.id) %>
<%= link_to "[Delete]", animal_path(@animal.id) ,method: :delete,data: { confirm: "Are you sure? "}%>

app/views/artiszoo/index.html.erb
<h1>Artiszoo</h1>

<% @artiszoos.each do |artiszoo| %>
  <p><%= link_to artiszoo.department, artiszoo_path(artiszoo.id) %></p>
<% end %>

app/views/artiszoo/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @artiszoo.department %></h1>
<h2>List of Animals</h2>
<% if @artiszoo.animals.any? %>
  <ul>
    <% @animals.each do |animal| %>
      <li><%= link_to animal.name, animal_path(animal.id) %></li>
    <% end %>
  </ul>
<%else%>
  <p>There are n animals in this artiszoo. </p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zoo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <br></br>
    <hr>
    <%= link_to "[All Animals]", animals_path %>
  </body>
</html>